df <- read.csv("household_power_consumption.txt", sep = ";", header = TRUE, na.strings = "?")
df$Date <- as.Date(df$Date, "%d/%m/%Y")
df <- subset(df, Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02"))
df$Time <- as.POSIXct(paste(df$Date, df$Time), format="%Y-%m-%d %H:%M:%S")
plot(df$Time, df$Sub_metering_1, type = "l", col = "black", xlab = NA, ylab = "Energy sub metering")
points(df$Time, df$Sub_metering_2, type = "l", col = "red")
points(df$Time, df$Sub_metering_3, type = "l", col = "blue")
legend("topright", lty = 1, col = c("black", "blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), pt.cex = 1, cex = 0.75)
dev.copy(png,"plot3.png")
dev.off()
dev.off()
rm(df)