df <- read.csv("household_power_consumption.txt", sep = ";", header = TRUE, na.strings = "?")
df$Date <- as.Date(df$Date, "%d/%m/%Y")
df <- subset(df, Date >= as.Date("2007-02-01") & Date <= as.Date("2007-02-02"))
df$Time <- as.POSIXct(paste(df$Date, df$Time), format="%Y-%m-%d %H:%M:%S")
plot(df$Time, df$Global_active_power, type = "l", xlab = NA, ylab = "Global Active Power (kilowatts)")
dev.copy(png,"plot2.png")
dev.off()
dev.off()
rm(df)